//
// Created by 12132 on 2022/10/22.
//

#ifndef BOOTSTRAP_SRC_CORE_COMPILER_ELEMENTS_INTRINSIC_H_
#define BOOTSTRAP_SRC_CORE_COMPILER_ELEMENTS_INTRINSIC_H_



class intrinsic {

};



#endif //BOOTSTRAP_SRC_CORE_COMPILER_ELEMENTS_INTRINSIC_H_
